In [1]:
import numpy as np

In [2]:
a = [1,2,3] * 100000000
len(a)

300000000

In [7]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.eye(6) + 2

array([[3., 2., 2., 2., 2., 2.],
       [2., 3., 2., 2., 2., 2.],
       [2., 2., 3., 2., 2., 2.],
       [2., 2., 2., 3., 2., 2.],
       [2., 2., 2., 2., 3., 2.],
       [2., 2., 2., 2., 2., 3.]])

In [11]:
np.eye(10,10,2)

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## operacje na tablicach

In [18]:
a = np.array([20,30,40,50]).reshape(2,2)
a

array([[20, 30],
       [40, 50]])

In [21]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [22]:
a+b

array([[20, 31],
       [42, 53]])

In [23]:
a-b

array([[20, 29],
       [38, 47]])

In [24]:
a*4

array([[ 80, 120],
       [160, 200]])

In [25]:
a @ b

array([[ 60, 110],
       [100, 190]])

In [26]:
a.dot(b)

array([[ 60, 110],
       [100, 190]])

In [30]:
a.sum()

140

In [32]:
a

array([[20, 30],
       [40, 50]])

In [31]:
a.sum(axis=0)

array([60, 80])

In [29]:
a.sum(axis=1)

array([50, 90])

In [33]:
np.sin(a)

array([[ 0.91294525, -0.98803162],
       [ 0.74511316, -0.26237485]])

In [36]:
a[1]

array([40, 50])

In [38]:
b = np.arange(100).reshape(10,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [39]:
b[2,3:7]

array([23, 24, 25, 26])

In [40]:
b[:4:2,3: ]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [23, 24, 25, 26, 27, 28, 29]])

## Indeksowanie, wycinanie, iterowanie - Indexing, Slicing and Iterating

Stwórz liste sześcianów liczb od 0 do 9

In [71]:
c = np.arange(10) ** 3
c

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

wybierz z listy zaznaczone elementy

In [44]:
m = [0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [46]:
m[2:5]

[8, 27, 64]

In [73]:
m[:5:2]

[0, 8, 64]

przekształć by otrzymać wynik

In [76]:
m[:5:2] = -1000
m

TypeError: must assign iterable to extended slice

[-1000, 1, -1000, 27, -1000, 125, 216, 343, 512, 729]

Odwróć listę